type Vehicle {
  id: ID!
  marque: String
  modele: String
  immatriculation: String
  statut: String
  driverId: ID
}

type Driver {
  id: ID!
  nom: String
  permis: String
  expiration: String
  assignedVehicleId: ID
}

type Location {
  vehicleId: ID!
  latitude: Float
  longitude: Float
  timestamp: String
}

type Maintenance {
  id: ID!
  vehicleId: ID!
  dateDebut: String
  dateFin: String
  type: String
  cout: Float
  description: String
  status: String
}

type Alerte {
  id: ID!
  vehicleId: ID
  type: String
  message: String
  timestamp: String
}

type Query {
  vehicles: [Vehicle]
  vehicle(id: ID!): Vehicle
  drivers: [Driver]
  driver(id: ID!): Driver
  vehicleLocationHistory(vehicleId: ID!): [Location]
  maintenance(vehicleId: ID!): [Maintenance]
  alertes(vehicleId: ID): [Alerte]
}

input VehicleInput {
  marque: String
  modele: String
  immatriculation: String
  statut: String
  driverId: ID
}

input DriverInput {
  nom: String
  permis: String
  expiration: String
  assignedVehicleId: ID
}

input MaintenanceInput {
  vehicleId: ID!
  type: String
  description: String
  cout: Float
  dateDebut: String
}

type Mutation {
  createVehicle(input: VehicleInput!): Vehicle
  createDriver(input: DriverInput!): Driver
  assignDriver(vehicleId: ID!, driverId: ID!): Vehicle
  createMaintenance(input: MaintenanceInput!): Maintenance
  closeMaintenance(id: ID!): Maintenance
}
