syntax = "proto3";

package location;

service LocationService {
  rpc StreamLocation (stream Location) returns (Ack) {}
  rpc GetVehicleLocationHistory (VehicleId) returns (LocationHistory) {}
  rpc ListVehicles (Empty) returns (VehicleList) {}

}

message Location {
  int64 vehicleId = 1;
  double latitude = 2;
  double longitude = 3;
  string timestamp = 4;
}

message Ack {
  bool success = 1;
  string message = 2;
}

message VehicleId {
  int64 id = 1;
}

message LocationHistory {
  repeated Location locations = 1;
}

message Empty {}

message Vehicle {
  int64 id = 1;
  double latitude = 2;
  double longitude = 3;
}

message VehicleList {
  repeated Vehicle vehicles = 1;
}

